### ISSUE TITLE
Feature request: echidna tests implementation outside of the contract.

### ISSUE THREAD

**Issue by cryptomental** [trailofbits/echidna#43]
Hi, I would like to execute Echidna tests without modifying original contracts, i.e. something along these lines:

Contract under test:

```
pragma solidity ^0.4.16;

contract C {

  int private state = 0;
  function f(int x) public {
    state = x;
  }
}
```

and C_echidna.sol with echidna tests:

```
import "C.sol";

pragma solidity ^0.4.16;

contract CEchidna is C {
  function echidna_revert() public returns (bool) {
    if (state < 0)
      revert();
  }
}
```

The idea is NOT to modify the contracts under test. 

Obviously the problem are private variables and functions as I have just experimented:

```
root@2ebd02bed9a2:/echidna# echidna-test solidity/echidna_tests/cli_echidna.sol Test --solc-args="--allow-paths=/echidna/solidity"
solidity/echidna_tests/cli_echidna.sol:10:12: Error: Undeclared identifier. Did you mean "log0"?
    return(flag0 || flag1);
           ^---^
solidity/echidna_tests/cli_echidna.sol:10:21: Error: Undeclared identifier. Did you mean "log1"?
    return(flag0 || flag1);
                    ^---^
echidna-test: readCreateProcess: solc "--combined-json=bin-runtime,bin,srcmap,srcmap-runtime,abi,ast" "solidity/echidna_tests/cli_echidna.sol" "--allow-paths=/echidna/solidity" (exit 1): failed
root@2ebd02bed9a2:/echidna# cat solidity/cli.sol 
pragma solidity ^0.4.16;

contract Test {
  bool private flag0=true;
  bool private flag1=true;

  function set0(int val) returns (bool){
    if (val % 10 == 0) {flag0 = false;}
  }
  function set1(int val) returns (bool){
    if (val % 10 == 0 && flag0) {flag1 = false;}
  }
  function echidna_alwaystrue() returns (bool){
    return(true);
  }
  function echidna_sometimesfalse() returns (bool){
    return(flag0 || flag1);
  }
}
```

Perhaps there would be a way to support this by having on-the-fly test injection into the original contract just before the test is executed. Does it make sense?

**Comment by cryptomental** [comment]
Hi @japesinator ! thanks for the reply. Inheritance did not work work me, as I wanted to develop tests based on private properties. See code in my comment above. The private properties are not accessible from the child contract, as confirmed here http://solidity.readthedocs.io/en/v0.4.23/contracts.html#visibility-and-getters . The main use case for me is that I would like to take any third-party Solidity project, write Echidna tests for it, and execute the tests without touching the original contract source code.

**Comment by japesinator** [comment]
I think that if what you want is really tests that reference private APIs without being in the same contract as those APIs are defined, you'd need a Solidity preprocessor of some sort (or a modified solc), and I can't say I'm super enthused about adding that kind of functionality to Echidna (seems a bit out of scope).

If you can think of a way to add this functionality without having to significantly manipulate the solidity compilation process I'd love to take a stab at implementing it, but otherwise I'm not sure I see this being merged into master.

If you (or anyone else) does end up implementing some kind of echidna-oriented preprocessor as a workaround here (I think you could do it in a couple lines of awk at most) please open-source it and let me know; Trail of Bits has bug bounties for all open source contributions and this would qualify for some money.

**Comment by cryptomental** [comment]
Thx @japesinator this is what I also came up with. A solidity preprocessor would likely do the job. I will close the ticket and will likely be back once I will be into implementing a solution.
